version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./backend/serviceAccountKey.json:/app/serviceAccountKey.json:ro

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - "80:80"

volumes:
  mongo-data:
